name = "ExponentialFamilies"
uuid = "e3f29fd2-98f1-11e9-2c12-071269efd997"
authors = ["Chad Scherrer <chad.scherrer@gmail.com>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
